### ISSUE TITLE
AttributeError: 'CVImage' object has no attribute 'set_blob'

### ISSUE THREAD

**Issue by EmmaThompson123** [ykk648/cv2box#3]
My cv2box version is 0.4.9, which version has the attribute 'set_blob' ?

**Comment by ykk648** [comment]
`set_blob` is deprecated,  you can use new API like `face_image_in = CVImage(self.face_image).blob_innormal(self.input_size, self.input_mean, self.input_std,rgb=False)` or `CVImage().blob`，I can help if you show me more codes releated.
